#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin.
# Build: compile src/ → lib/ with the dsh checkout's tsc.
# Requires DSH_CHECKOUT pointing at a dsh source checkout (auto-probe below).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# DSH_CHECKOUT 探测：环境变量 → 常见路径（home 下 dsh-harness）
CHECKOUT="${DSH_CHECKOUT:-}"
if [ -z "$CHECKOUT" ]; then
  for candidate in "$HOME/dsh-harness" "$HOME/dsh" "$HOME/.dsh/dsh-harness"; do
    if [ -d "$candidate/packages" ]; then CHECKOUT="$candidate"; break; fi
  done
fi
if [ -z "$CHECKOUT" ] || [ ! -d "$CHECKOUT/packages" ]; then
  echo "build: cannot locate the dsh checkout (set DSH_CHECKOUT)" >&2
  exit 1
fi

TSC="$CHECKOUT/node_modules/.bin/tsc"
if [ ! -x "$TSC" ] && [ ! -f "$TSC.cmd" ]; then
  echo "build: tsc not found at $TSC" >&2
  exit 1
fi

link_pkg() {
  local target="$CHECKOUT/$2"
  if [ ! -e "$target" ]; then
    echo "build: dependency target missing: $target" >&2
    exit 1
  fi
  node -e "
    const fs = require('fs');
    const path = require('path');
    const link = path.resolve(process.argv[1]);
    const target = path.resolve(process.argv[2]);
    fs.rmSync(link, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(link), { recursive: true });
    fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
  " "node_modules/$1" "$target"
}

echo "=== Linking build dependencies (checkout: $CHECKOUT) ==="
mkdir -p node_modules/@deepseek-ai
node -e "const fs=require('fs');fs.rmSync('node_modules/@standard-schema',{recursive:true,force:true})"
link_pkg cordis vendor/cordis
link_pkg cosmokit vendor/cosmokit
link_pkg schemastery vendor/schemastery
link_pkg @deepseek-ai/dsh-tools packages/core/tools
link_pkg @deepseek-ai/dsh-llm packages/llm/llm
link_pkg @deepseek-ai/dsh-session packages/core/session
link_pkg @deepseek-ai/dsh-subagent packages/subagent/subagent
mkdir -p node_modules/@a2a-js
A2A_SDK="${A2A_SDK_PATH:-}"
if [ -z "$A2A_SDK" ]; then
  A2A_SDK=$(node -e "
    const fs = require('fs');
    const path = require('path');
    const { createRequire } = require('module');
    const req = createRequire(path.resolve(process.argv[1], 'package.json'));
    let current = req.resolve('@a2a-js/sdk');
    while (!fs.existsSync(path.join(current, 'package.json'))) {
      const parent = path.dirname(current);
      if (parent === current) process.exit(1);
      current = parent;
    }
    process.stdout.write(current);
  " "$CHECKOUT/packages/a2a/a2a-protocol") || true
fi
if [ -z "$A2A_SDK" ] || [ ! -e "$A2A_SDK" ]; then
  echo "build: cannot locate @a2a-js/sdk in the dsh checkout" >&2
  exit 1
fi
node -e "
  const fs = require('fs');
  const path = require('path');
  fs.rmSync('node_modules/@a2a-js/sdk', { recursive: true, force: true });
  fs.symlinkSync(path.resolve(process.argv[1]), path.resolve('node_modules/@a2a-js/sdk'), process.platform === 'win32' ? 'junction' : 'dir');
" "$A2A_SDK"
# @types/node（编译类型；checkout 自带）
link_pkg @types/node node_modules/@types/node

STD_SCHEMA=$(find "$CHECKOUT/node_modules/.pnpm" -maxdepth 1 -type d -iname '@standard-schema+spec@*' 2>/dev/null | head -1)
if [ -n "$STD_SCHEMA" ]; then
  node -e "
    const fs = require('fs');
    const path = require('path');
    fs.rmSync('node_modules/@standard-schema', { recursive: true, force: true });
    fs.mkdirSync('node_modules/@standard-schema', { recursive: true });
    fs.symlinkSync(path.resolve(process.argv[1]), path.resolve('node_modules/@standard-schema/spec'), process.platform === 'win32' ? 'junction' : 'dir');
  " "$STD_SCHEMA/node_modules/@standard-schema/spec"
fi

echo "=== Compiling src → lib ==="
"$TSC" -p tsconfig.json

TSDOWN="$CHECKOUT/node_modules/.bin/tsdown"
if [ -x "$TSDOWN" ] || [ -f "$TSDOWN.cmd" ]; then
  echo "=== Bundling host lib ==="
  "$TSDOWN" --config tsdown.config.ts
else
  echo "build: tsdown not found; skipping bundle (lib remains tsc output)" >&2
fi

echo "=== Build complete ==="
